export const DATA_LOGIN = "DATA_LOGIN";
export const DATA_FROM_TOKEN = "DATA_FROM_TOKEN";
export const DELETE_DATA_LOGIN = "DELETE_DATA_LOGIN";
export const GET_USERS = "GET_USERS";
export const GET_USER_ID = "GET_USER_ID";
export const GET_CASE = "GET_CASE";
export const GET_CASE_ID = "GET_CASE_ID";
export const ADD_CASE = "ADD_CASE";
export const DELETE_CASE = "DELETE_CASE";
export const UPDATE_CASE = "UPDATE_CASE";
export const EDIT_CASE = "EDIT_CASE";
export const SEARCH_CASE = "SEARCH_CASE";
export const GET_ORGANIZATION_BY_ID = "GET_ORGANIZATION_BY_ID";
export const GET_SAMPLE_BY_LITIGANT_ID = "GET_SAMPLE_BY_LITIGANT_ID";

// export const UPDATE_CASE_STATUS = "UPDATE_CASE_STATUS";
export const GET_SAMPLE_BY_CASE_ID = "GET_SAMPLE_BY_CASE_ID";
export const ADD_SAMPLE = "ADD_SAMPLE";
export const VIEW_SAMPLE = "VIEW_SAMPLE";
export const DELETE_SAMPLE = "DELETE_SAMPLE";
export const UPDATE_SAMPLE = "UPDATE_SAMPLE";
export const EDIT_SAMPLE = "EDIT_SAMPLE";
export const SEARCH_SAMPLE = "SEARCH_SAMPLE";
export const UPDATE_SAMPLE_STATUS = "UPDATE_SAMPLE_STATUS";

// GET STEP BY SAMPLE ID
export const GET_EXTRACT_STEP_BY_SAMPLE_ID = "GET_EXTRACT_STEP_BY_SAMPLE_ID";
export const GET_PRC_STEP_BY_SAMPLE_ID = "GET_PRC_STEP_BY_SAMPLE_ID";
export const GET_ELECTRO_STEP_BY_SAMPLE_ID = "GET_ELECTRO_STEP_BY_SAMPLE_ID";
export const GET_PURIFY_STEP_BY_SAMPLE_ID = "GET_PURIFY_STEP_BY_SAMPLE_ID";
export const GET_RESULT_STEP_BY_SAMPLE_ID = "GET_RESULT_STEP_BY_SAMPLE_ID";


// POST(ADD) STEP BY SAMPLE ID
export const ADD_EXTRACT_STEP_BY_SAMPLE_ID = "ADD_EXTRACT_STEP_BY_SAMPLE_ID";
export const ADD_PRC_STEP_BY_SAMPLE_ID = "ADD_PRC_STEP_BY_SAMPLE_ID";
export const ADD_ELECTRO_STEP_BY_SAMPLE_ID = "ADD_ELECTRO_STEP_BY_SAMPLE_ID";
export const ADD_PURIFY_STEP_BY_SAMPLE_ID = "ADD_PURIFY_STEP_BY_SAMPLE_ID";
export const ADD_RESULT_STEP_BY_SAMPLE_ID = "ADD_RESULT_STEP_BY_SAMPLE_ID";


// GET (GET DATA) STEP BY SAMPLE
export const GET_VALUE_EXTRACT_STEP_BY_SAMPLE_ID = "GET_VALUE_EXTRACT_STEP_BY_SAMPLE_ID";
export const GET_VALUE_PRC_STEP_BY_SAMPLE_ID = "GET_VALUE_PRC_STEP_BY_SAMPLE_ID";
export const GET_VALUE_ELECTRO_STEP_BY_SAMPLE_ID = "GET_VALUE_ELECTRO_STEP_BY_SAMPLE_ID";
export const GET_VALUE_PURIFY_STEP_BY_SAMPLE_ID = "GET_VALUE_PURIFY_STEP_BY_SAMPLE_ID";
export const GET_VALUE_RESULT_STEP_BY_SAMPLE_ID = "GET_VALUE_RESULT_STEP_BY_SAMPLE_ID";


// PUT(EDIT) STEP BY SAMPLE ID
export const EDIT_EXTRACT_STEP_BY_SAMPLE_ID = "EDIT_EXTRACT_STEP_BY_SAMPLE_ID";
export const EDIT_PRC_STEP_BY_SAMPLE_ID = "EDIT_PRC_STEP_BY_SAMPLE_ID";
export const EDIT_ELECTRO_STEP_BY_SAMPLE_ID = "EDIT_ELECTRO_STEP_BY_SAMPLE_ID";
export const EDIT_PURIFY_STEP_BY_SAMPLE_ID = "EDIT_PURIFY_STEP_BY_SAMPLE_ID";
export const EDIT_RESULT_STEP_BY_SAMPLE_ID = "EDIT_RESULT_STEP_BY_SAMPLE_ID";



// Kit Action
export const GET_KIT = "GET_KIT";
export const ADD_KIT = "ADD_KIT";
export const EDIT_KIT = "EDIT_KIT"
export const UPDATE_KIT = "UPDATE_KIT";
export const SEARCH_KIT = "SEARCH_KIT";
export const FILTER_BY_NAME_KIT = "FILTER_BY_NAME_KIT";

// GET KIT STEP
export const GET_KIT_EXTRACT_BY_ID = "GET_KIT_EXTRACT_BY_ID";
export const GET_KIT_PRC_BY_ID = "GET_KIT_PRC_BY_ID";
export const GET_KIT_ELECTRO_BY_ID = "GET_KIT_ELECTRO_BY_ID";
export const GET_KIT_PURIFY_BY_ID = "GET_KIT_PURIFY_BY_ID";

// GET SELECT SYSTEM 
export const GET_SELECT_EXTRACT_ADN_SYSTEM_BY_ID = " GET_SELECT_EXTRACT_ADN_SYSTEM_BY_ID";
export const GET_SELECT_EXTRACT_EXTRACT_SYSTEM_BY_ID = "GET_SELECT_EXTRACT_EXTRACT_SYSTEM_BY_ID";
export const GET_SELECT_PRC_PRC_SYSTEM_BY_ID = "GET_SELECT_PRC_PRC_SYSTEM_BY_ID";
export const GET_SELECT_ELECTRO_ELECTRO_SYSTEM_BY_ID = "GET_SELECT_ELECTRO_ELECTRO_SYSTEM_BY_ID";

// GET LOG 
export const GET_EXTRACT_LOG_BY_SAMPLE_ID = "GET_EXTRACT_LOG_BY_SAMPLE_ID";
export const GET_PCR_LOG_BY_SAMPLE_ID = "GET_PCR_LOG_BY_SAMPLE_ID";
export const GET_ELECTRO_LOG_BY_SAMPLE_ID = "GET_ELECTRO_LOG_BY_SAMPLE_ID";
export const GET_PURIFY_LOG_BY_SAMPLE_ID = "GET_PURIFY_LOG_BY_SAMPLE_ID";
export const GET_RESULT_LOG_BY_SAMPLE_ID = "GET_RESULT_LOG_BY_SAMPLE_ID";


// ADD LOG 
export const ADD_EXTRACT_LOG = "ADD_EXTRACT_LOG";
export const ADD_PRC_LOG = "ADD_PRC_LOG";
export const ADD_ELECTRO_LOG = "ADD_ELECTRO_LOG";
export const ADD_PURIFY_LOG = "ADD_PURIFY_LOG";
export const ADD_RESULT_LOG = "ADD_RESULT_LOG";


// Litigant Action
export const GET_LITIGANT = "GET_LITIGANT";
export const ADD_LITIGANT = "ADD_LITIGANT";
export const EDIT_LITIGANT = "EDIT_LITIGANT";
export const UPDATE_LITIGANT = "UPDATE_LITIGANT";
export const SEARCH_LITIGANT = "SEARCH_LITIGANT";
export const FILTER_BY_NAME_LITIGANT = "FILTER_BY_NAME_LITIGANT";
// System Action
export const GET_SYSTEM = "GET_SYSTEM";
export const ADD_SYSTEM = "ADD_SYSTEM";
export const EDIT_SYSTEM = "EDIT_SYSTEM";
export const UPDATE_SYSTEM = "UPDATE_SYSTEM";
export const SEARCH_SYSTEM = "SEARCH_SYSTEM";
export const FILTER_BY_NAME_SYSTEM = "FILTER_BY_NAME_SYSTEM";
// Organization Action
export const GET_ORGANIZATION = "GET_ORGANIZATION";
export const ADD_ORGANIZATION = "ADD_ORGANIZATION";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const EDIT_ORGANIZATION = "EDIT_ORGANIZATION";
export const SEARCH_ORGANIZATION = "SEARCH_ORGANIZATION"
export const FILTER_BY_NAME_ORGANIZATION  ="FILTER_BY_NAME_ORGANIZATION"
//Notifiation Action
export const CREATE_NOTIFICATION = "CREATE_NOTIFIATION";
export const CREATE_NOTIFICATION_ERROR = "CREATE_NOTIFICATION_ERROR";

// export const GET_SAMPLE_STATUS = "GET_SAMPLE_STATUS";
// export const UPDATE_SAMPLE_STATUS = "UPDATE_SAMPLE_STATUS";
// du me may nhu cai lon 
// FILTER HEREE

